# The options for "/wrath drown"
Drown:
    # The message to display when a player is killed with this command (leave blank for none).
    Message: "%target% was slowly drowned by %player%."
# The options for "/wrath explode"
Explode:
    # The message to display when a player is killed with this command (leave blank for none).
    Message: "%target% exploded after %player% replaced their blood with nitroglycerin."
    # The number of seconds to countdown before exploding (set to 0 for an instant explosion).
    Seconds: 5
# The options for "/wrath strike"
Strike:
    # The message to display when a player is killed with this command (leave blank for none).
    Message: "%player% struck %target% down with lightning."