# Messages that can be displayed when a wrath action is executed.
Messages:
    # The message to display for "/wrath strike" (leave blank for none).
    Strike: "%player% struck %target% down with lightning"