# The options for "/wrath drown"
Drown:
    # The message to display when a player is killed with this command (leave blank for none).
    Message: "%target% was slowly drowned by %player%"
# The options for "/wrath strike"
Strike:
    # The message to display when a player is killed with this command (leave blank for none).
    Message: "%player% struck %target% down with lightning"