name: Wrath
main: me.ryall.wrath.Wrath
version: 1.1.0
description: Kill annoying players in a multitude of horrible ways.
author: SirHedgehog
commands:
    wrath:
        description: Wrath command
        usage: /wrath <death> <player>